# Appendix A

## Finite Elements History:

Mikhlin (1964) in the western
literature to the appearance of the book by Strang and Fix (1973), which
describes very lucidly the mathematical achievements of the period. Perhaps,
from a historical perspective, the book by Strang and Fix will be seen as the
epitaph of the variational era.
The later status of the finite-element method, from a mathematical perspec-
tive, is succinctly set out in Oden and Reddy (1976a) and by Mitchell and
Wait (1977). An engineering perspective is given in Heubner (1975), Bathe and
Wilson (1976), Zienkiewicz (1977), and Irons and Ahmad (1980). More
specialized books on the finite-element method are provided by Oden (1972)
on nonlinear continuum mechanics, Temam (1979b) on the Navier-Stokes
equations, Pinder and Gray (1977) on groundwater and tidal flows, and
Brebbia (1978) on boundary-element methods.

Glibert Strang: 
- Galerkin Forumlated the idea of stitching together 1 or 2 test functions that would give close approximation to the true solution
- Then around the 1940s, Courant (a German-American) and simultaneously others including in Europe/China started thinking about haveing many simpler test functions and feeding them into a computer.
- Then other ideas came, about using other different trial functions.
- One idea is also to use wavelets as Trial functions.


# Appendix B

## Lagrange Polynomials

Genral Formulae for N gird points, starting for index 0 to (n-1): 

$ L_j^{(n-1)}(x) = \prod_{\substack{i=0 \\ i \ne j}}^{n-1} \frac{x - x_i}{x_j - x_i} $

Degree n=1
N=2 grid points 

$
L_0^{(1)}(x) = \prod_{\substack{i=0 \\ i \ne 0}}^{1} \frac{x - x_i}{x_0 - x_i} = \frac{x - x_1}{x_0 - x_1}
$

$
L_1^{(1)}(x) = \prod_{\substack{i=0 \\ i \ne 1}}^{1} \frac{x - x_i}{x_1 - x_i} = \frac{x - x_0}{x_1 - x_0}
$


Degree n=2
N=3 grid points 

$
L_0^{(2)}(x) = \prod_{\substack{i=0 \\ i \ne 0}}^{2} \frac{x - x_i}{x_0 - x_i} 
= \frac{x - x_1}{x_0 - x_1} \cdot \frac{x - x_2}{x_0 - x_2}
$

$
L_1^{(2)}(x) = \prod_{\substack{i=0 \\ i \ne 1}}^{2} \frac{x - x_i}{x_1 - x_i} 
= \frac{x - x_0}{x_1 - x_0} \cdot \frac{x - x_2}{x_1 - x_2}
$

$
L_2^{(2)}(x) = \prod_{\substack{i=0 \\ i \ne 2}}^{2} \frac{x - x_i}{x_2 - x_i} 
= \frac{x - x_0}{x_2 - x_0} \cdot \frac{x - x_1}{x_2 - x_1}
$

## Calculating Shape functions for Quadrilateral Elements

Reference square $[\xi_0, \xi_1] *[\eta_0, \eta_1] $= [0,1] x [0,1]:

    η
    ^
    |
     4----3
     |    |
     |    |
     1----2 
    --> ξ



General 1D Lagrange polynomials:

For ξ-direction $ [\xi_0, \xi_1] = [0, 1] $ :

$L_0^{(1)}(\xi) = \frac{\xi - \xi_1}{\xi_0 - \xi_1} = 1 - \xi$

$L_1^{(1)}(\xi) = \frac{\xi - \xi_0}{\xi_1 - \xi_0} = \xi$

Thus:
$
L_0(\xi) = 1 - \xi, \quad L_1(\xi) = \xi
$


For η-direction $ [\eta_0, \eta_1] = [0, 1] $:  

$ L_0^{(1)}(\eta) = \frac{\eta - \eta_1}{\eta_0 - \eta_1} = 1 - \eta $

$ L_1^{(1)}(\eta) = \frac{\eta - \eta_0}{\eta_1 - \eta_0} = \eta $

Thus:
$
L_0(\eta) = 1 - \eta, \quad L_1(\eta) = \eta
$

| Shape function | $L_i^{(1)}(\xi)$ | $L_j^{(1)}(\eta)$ | Formula |
|----------------|------------|------------|---------|
| $\phi_1(\xi,\eta) = L_0(\xi).L_0(\eta)$ | $1-\xi$ | $1-\eta$ | $(1-\xi)(1-\eta)$ |
| $\phi_2(\xi,\eta) = L_1(\xi).L_0(\eta)$ | $\xi$    | $1-\eta$ | $\xi(1-\eta)$ |
| $\phi_3(\xi,\eta) = L_1(\xi).L_1(\eta)$ | $\xi$    | $\eta$   | $\xi \eta$ |
| $\phi_4(\xi,\eta) = L_0(\xi).L_1(\eta)$ | $1-\xi$ | $\eta$   | $(1-\xi)\eta$ |

Note: Each shape function value above is some product of both  $\xi, \eta$

| Shape function | $\frac{\partial \phi_i}{\partial \xi}$ | $\frac{\partial \phi_i}{\partial \eta}$ |
|----------------|---------------------------------------|---------------------------------------|
| $\nabla\phi_1$ | $-(1-\eta)$ | $-(1-\xi)$ |
| $\nabla\phi_2$ | $1-\eta$    | $-\xi$      |
| $\nabla\phi_3$ | $\eta$      | $\xi$       |
| $\nabla\phi_4$ | $-\eta$     | $1-\xi$     |


Each element of the Jacobian Matrix is a dot product of two 4 by 1 vectors:  

$
\frac{\partial x}{\partial \xi}=
\begin{bmatrix}
x_1 & x_2 & x_3 & x_4
\end{bmatrix}
\begin{bmatrix}
\dfrac{\partial \phi_1}{\partial \xi} \\
\dfrac{\partial \phi_2}{\partial \xi} \\
\dfrac{\partial \phi_3}{\partial \xi} \\
\dfrac{\partial \phi_4}{\partial \xi}
\end{bmatrix}
$

$
\frac{\partial y}{\partial \eta}=
\begin{bmatrix}
y_1 & y_2 & y_3 & y_4
\end{bmatrix}
\begin{bmatrix}
\dfrac{\partial \phi_1}{\partial \eta} \\
\dfrac{\partial \phi_2}{\partial \eta} \\
\dfrac{\partial \phi_3}{\partial \eta} \\
\dfrac{\partial \phi_4}{\partial \eta}
\end{bmatrix}
$


## Shape Functions for 1D Case

Shape functions are usually defined for 1D by stitching together two Lagrange Polynomials over adjacent elements to create  a Hat Function .<br>
This is shown as $\phi_i(x)$ for element i defined over $ [x_i , x_{i+1}]$ defined below:

$
\phi_i(x) = \begin{cases}
   L_i^{(1)}(x) = \frac{x - x_{i-1}}{x_i - x_{i-1}} = \frac{x - x_{i-1}}{h}  &\text{if } x \in [x_{i-1}, x_i ] 
   \\ 
   L_i^{(1)}(x) = \frac{x - x_{i+1}}{x_i - x_{i+1}} = \frac{x - x_{i+1}}{-h}  &\text{if } x \in [x_i , x_{i+1}] 
   \\
   0 &\text{else }
\end{cases}
$

$
\phi_i(x) =
\begin{cases}
\dfrac{x - x_{i-1}}{h}, & x \in [x_{i-1}, x_i], \\[1ex]
\dfrac{x_{i+1} - x}{h}, & x \in [x_i, x_{i+1}], \\[1ex]
0, & \text{otherwise},
\end{cases}
$

$
\phi_i(x) = L_i^{(1)}(x) :=
\begin{cases}
\dfrac{x - x_{i-1}}{x_i - x_{i-1}}, & x \in [x_{i-1}, x_i], \\[1ex]
\dfrac{x_{i+1} - x}{x_{i+1} - x_i}, & x \in [x_i, x_{i+1}], \\[1ex]
0, & \text{otherwise}.
\end{cases}
$

where h is nodal distances over the mesh points.

<img src=image.png style='width: 35%;'>

# Appendix C

## Important Matrix operations  in Python / Numpy

### Matrix Basics in Python

#### Tip 1. ALWAYS use np.array[ ] for Linear Algebra / Maths

In [ ]:
import numpy as np

# Example 1 : BAD
B = [[1, 2, 3],   # row 0
     [4, 5, 6]]   # row 1   
print(type(B))  # Output: <class 'list'>
print(B[0][1])  # Access element at row 0, column 1 --> Output: 2   

# Example 2 : GOOD
# Use numpy arrays, more efficient, designed for numerical computations
A = np.array([
    [1, 2, 3],   # row 0
    [4, 5, 6]    # row 1
])
print(type(A))      # Output: <class 'numpy.ndarray'>
print(A[0, 1])       # Access element at row 0, column


<class 'list'>
2
<class 'numpy.ndarray'>
2


In [ ]:
# Example 3 : Matrix of shape (2,3)
A = np.array([
    [1, 2, 3],   # row 0
    [4, 5, 6]    # row 1
])

print(A.shape) # Output (rows, columns) = (2, 3) 
print(A)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print(A + B)      # [5 7 9]
print(A * 2)      # [2 4 6], broadcasting

# term-wise multiplication, not matrix multiplication
print(A * B)      # [4 10 18]

# For matrix multiplication, use np.dot or @ operator
np.dot(A, B)      # matrix multiply

# More operations
I = np.eye(3)  # identity matrix 3x3

A  = np.random.rand(2, 3)  
B  = np.random.rand(3, 2)  
C  = A @ B  # matrix multiplication

print(C)

np.linalg.inv(I)  # inverse

np.sum(A, axis=0) # sum along columns


[5 7 9]
[2 4 6]
[ 4 10 18]
[[1.45933702 0.69444572]
 [0.9372808  0.47030522]]


array([1.33396604, 1.24697468, 1.03419988])

### Tip 2:  Use Reshape

In [20]:
# Example 1: Reshaping Simple Arrays
flat = [1, 2, 3, 4, 5, 6] 

# Convert to numpy array, then reshape
A = np.array(flat).reshape((2, 3))

print(A.shape) # Output: (6, )
print(A)

(2, 3)
[[1 2 3]
 [4 5 6]]


### Tip 3 : Use Enumerate 

A bit tricky how it works but following example can show how to use them in loops

In [23]:
# Example 1
for i, j in enumerate( np.array([5, 6, 7, 8]) ):
    print(f"i={i}, j={j}")


i=0, j=5
i=1, j=6
i=2, j=7
i=3, j=8


In [24]:
arr2d = np.array([
    [1, 2], 
    [3, 4], 
    [5, 6]
])

for i, row in enumerate(arr2d):
    print(f"Row {i}: {row}")


Row 0: [1 2]
Row 1: [3 4]
Row 2: [5 6]


In [33]:
# Example : Enumerate a 2D matrix
matrix = [
    [1, 2, 3, 4], 
    [5, 6, 7, 8]
]

for i, row in enumerate(matrix):
    for j, val in enumerate(row):
        print(f"Element ( {i} , {j} ) = {val}")


Element ( 0 , 0 ) = 1
Element ( 0 , 1 ) = 2
Element ( 0 , 2 ) = 3
Element ( 0 , 3 ) = 4
Element ( 1 , 0 ) = 5
Element ( 1 , 1 ) = 6
Element ( 1 , 2 ) = 7
Element ( 1 , 3 ) = 8


### Tip 4 : Sparse Matrices

In [34]:
from scipy.sparse import csr_matrix

rows = [0, 0, 1, 1]
cols = [0, 0, 1, 1]
data = [1, 2, 3, 4]  # duplicate indices (0,0) and (1,1)
A = csr_matrix((data, (rows, cols)), shape=(2,2))
print(A.toarray())


[[3 0]
 [0 7]]


# Appendix D  

## Code - Assemble Stiffness Matrices (non-vectorized)

In [ ]:
from scipy.sparse import coo_matrix
from scipy.sparse import coo_matrix
import numpy as np

from scipy.sparse import coo_matrix
from scipy.sparse import coo_matrix
import numpy as np

def Assemble(S, F, M, nodes, E, N):
    nL = nodes.shape[1]  # Nodes per Element

    # Initialize sparse matrices using LIL format for efficient assembly
    Sg = lil_matrix((N, N))
    Mg = lil_matrix((N, N))
    Fg = np.zeros(N)
    
    for i in range(E):  # Loop over all elements E (Quads or Triangles)

        for idx_i, i_G in enumerate(nodes[i]):      # Loop over nodes of  Element i
            Fg[i_G] += F[idx_i, 0, i] 

            for idx_J, j_G in enumerate(nodes[i]):  # Loop over nodes of  Element i
                Sg[i_G, j_G] += S[idx_i, idx_J, i]
                Mg[i_G, j_G] += M[idx_i, idx_J, i]

            # Why Loop twice over element nodes?
            #  Because Each S, M are nL x nL matrices per element

    # Convert to CSR for fast arithmetic / solving
    return Sg.tocsr(), Fg, Mg.tocsr()

